# the main source of inspiration for this website was https://sta210-s22.github.io/website/ and https://github.com/sta210-s22/website

project:
  type: website
  output-dir: docs # command to allow publishing using docs (https://quarto.org/docs/publishing/github-pages.html)
  # to render the website I can use terminal and issue "quarto render"

website:
  title: "ABEM_22-23"
  description: "Homepage for ABEM - Applied Bioinformatic for Molecular Ecology, Fall 2022."
  open-graph: true
  
  sidebar:
    background: "#D9E3E4"
    logo: ./images/background.jpg
    pinned: true
    align: center
    tools:
      - icon: github
        href: https://github.com/GiulianoColosimo/abem_22-23.git
        text: "GitHub organization"


    style: "docked"
    search: true
    collapse-level: 1
    contents:
      - section: "Course information"
        contents:
          - href: index.qmd
            text: "Overview"
          - href: course_syllabus.qmd
            text: "Syllabus"
          - href: course_schedule.qmd
            text: "Schedule"
      - section: "Classes"
        contents:
           - ./classes/class1.qmd
           - ./classes/class2.qmd
           - ./classes/class3.qmd
      - href: contacts.qmd
        text: Contacts

   
  page-footer:
    right: "This page is built with ❤️ and [Quarto](https://quarto.org/). The format is inspired by this [course page](https://sta210-s22.github.io/website/)"
    left: "&copy; Copyright 2022, Giuliano Colosimo and Giulia Maiello"
    background: "#D9E3E4"


format:
  html:
    theme:
      light: [cosmo, theme.scss]
      dark: [cosmo, theme-dark.scss]
    mainfont: "Atkinson Hyperlegible"
    code-copy: true
    code-overflow: wrap
    toc: true

freeze: auto

editor: visual


