---
title: "Syllabus"
author: Giuliano Colosimo and Giulia Maiello
date: "`r Sys.Date()`"
---

## General information

This is an discretionary course for master level students enrolled in the "Biologia Evoluzionistica, Ecologia e Antropologia Applicata" degree at the University of Rome Tor Vergata. It is worth **3 CFU** for a total of 24 hours to be administered in person (or remotely, depending on the evolution of the pandemic) during the first semester of academic year 2022/2023.

|          | Day       | Time                | Location   |
|----------|-----------|---------------------|------------|
| Lectures | Tue & Thu | 10:00 pm - 12:00 pm | Televisore |

:::{.callout-note}
Attendance is mandatory!
:::

## Course language

The course will be thought in Italian unless international students are present. In this latter case the course will be thought in English. All the material and the literature used (including this website!) will be in English.

## Pre-requisites

This is an introductory course, so no prior knowledge of this topic is required. Throughout the course students will be extensively exposed to various software and web-tools. All software used is freely available and relatively easy to install. It is necessary that each student has his/her own laptop in order to better follow the various demonstrations/exercises that will take place in class. Problem-solving skills and a good knowledge of your own computer OS structure and function will definitely be useful. This course does not teach you system administration skills and you should know how to read help files and software guides, as well as retrieve information on-line. Should a student not have a portable computer, all code and demonstrations will be uploaded on this website and are available for practice on a desktop computer.

:::{.callout-warning}
Note that most modern bioinformatic relies on Unix-based systems (macOS and Linux). That being said, the material covered in class should work fine on Windows systems as well!
:::

## Textbook

As this is an introductory and discretionary course we decided not to adopt a textbook. This is not to say that there are no introductory texts available (some of them are actually really good!). For those of you with a deep interest in Bioinformatics we recommend, as starters, the following books:

- [Bioinformatics Data Skill](https://www.oreilly.com/library/view/bioinformatics-data-skills/9781449367480/)
- [Bioinformatics for Beginners: Genes, Genomes, Molecular Evolution, Databases and Analytical Tools](https://www.sciencedirect.com/book/9780124104716/bioinformatics-for-beginners)

## Additional Resources

As this course will heavily rely on the use of R we report here some very useful resources that we encourage to use.

- [StackOverflow](https://stackoverflow.com)
- [Bioconductor](http://www.bioconductor.org)
- [Modern Statistics for Modern Biology](https://www.huber.embl.de/msmb/index.html)
- [Un Viaggio nell'Ambiente R](https://tommaso-russo.github.io/libroR/index.html)

## Learning objectives

By the end of the course a student should be able to:

-   Know the basics of different sequencing technologies;
-   Work with common genetic and genomic data file (FASTA and FASTAQ);
-   Learn how to use the R language to analyse large genomic data set;
-   Learn how to perform small, reproducible bioinformatic projects;
-   Query and obtain data from on-line nucleotide sequence databases;
-   Perform basic ecological analyses from genomic data.

## Class evaluation

The assessment of the students' learning level will take place throughout the course,  

Students' evaluation is based on three main aspects:

1. Participation to class and discussions;
2. Paper presentation;
3. Project.

### Participation to class and discussion

Through the discussion of primary literature on the main subject. The critical comparison of the various methodologies of data acquisition, organization and processing will constitute the basis for the formulation of the student's final judgment. Aspects that will be used to assess students' learning level are their participation and interaction during the course and their ability to present and discuss scientific literature articles.

### Paper presentation

Each student will, taking turns, be assigned a paper that he/she will present at the beginning of the next class. The presentation should consist of a PowerPoint (or .pdf or .slides) no longer than 20 minutes (~15 slides). At the end of each presentation the audience will have 10 minutes to ask questions or discuss the material presented. Each student in the audience has to prepare at least one question to ask the presenter.

::: {.callout-important}
Even if you are not presenting the paper you still have to read it carefully to prepare your question and actively participate in the discussion!!
:::

### Project 

Towards the end of class each student will be assigned a data set. To pass the course with full marks, the student should submit a report related to a project that he/sge would have developed starting from the assigned data set. Each student will have to use all the skills acquired during class, analyse the data set and submit the final project for evaluation. All the instructions on how to format the final report will be illustrated in class and added on this website.

### Grading

| Category              | Percentage      |
|-----------------------|-----------------|
| Participation         | 15%             |
| Paper Presentation    | 35%             |
| Project               | 50%             |



