---
title: "Schedule"
author: Giuliano Colosimo and Giulia Maiello
date: "`r Sys.Date()`"
tbl-colwidths: [5,10,15]
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(calendR)
```

```{r calendar1, echo=FALSE, message=FALSE, warning=FALSE}
# Vector of dates
dates <- seq(as.Date("2022-10-01"), 
  as.Date("2022-10-31"), by = "1 day")

# Vector of NA and weekends
# (with the week starting on Monday)
events <- ifelse(format(dates, "%w") %in% c(6, 0), "Weekend", NA)

events[c(17, 20, 24, 27)] <- "Classes"

calendR(year = 2022, 
        month = 10, 
        start = "M",
        title = "Class calendar",
        subtitle = "October 2022",
        special.days = events,
        special.col = c("#00AAAE", "gray"),
        low.col = "white",
        legend.pos = "bottom", # Legend position
        legend.title = "",
        text = c("11:00-13:00\nMeet & Greet\nPC set up",
                 "16:00-18:00\nStudy design and Lab work", 
                 "11:00-13:00\nSeq. technologies",
                 "16:00-18:00\nNGS and case studies"),             
        text.pos = c(17, 20, 24, 27),        
        text.size = 2.5,              
        text.col = "black")
```

```{r calendar_2, echo=FALSE, message=FALSE, warning=FALSE}
# Vector of dates
dates <- seq(as.Date("2022-11-01"), as.Date("2022-11-30"), by = "1 day")

# Vector of NA and weekends
# (with the week starting on Monday)
events <- ifelse(format(dates, "%w") %in% c(6, 0), "Weekend", NA)

events[c(3, 7, 10, 14, 17, 21, 24, 28)] <- "Classes"

calendR(year = 2022, 
        month = 11, 
        start = "M",
        title = "",
        subtitle = "November 2022",
        special.days = events,
        special.col = c("#00AAAE", "gray"),
        low.col = "white",
        legend.pos = "bottom", # Legend position
        legend.title = "",
        text = c("16:00-18:00\nPipeline 1",
                 "11:00-13:00\nPipeline 2",
                 "16:00-18:00\nPipeline 3",
                 "11:00-13:00\nPipeline 4",
                 "16:00-18:00\nAlternative pipelines",
                 "11:00-13:00\nEcological implications",
                 "16:00-18:00\nR-markdown",
                 "11:00-13:00\nRecap and Proj. assignment"),             
        text.pos = c(3, 7, 10, 14, 17, 21, 24, 28),        
        text.size = 2.5,              
        text.col = "black")
```

```{r calendar_3, echo=FALSE, message=FALSE, warning=FALSE}
# Vector of dates
dates <- seq(as.Date("2022-12-01"), as.Date("2022-12-31"), by = "1 day")

# Vector of NA and weekends
# (with the week starting on Monday)
events <- ifelse(format(dates, "%w") %in% c(6, 0), "Weekend", NA)

events[23] <- "Exam"

calendR(year = 2022, 
        month = 12, 
        start = "M",
        title = "",
        subtitle = "December 2022",
        special.days = events,
        special.col = c("Red", "gray"),
        low.col = "white",
        legend.pos = "bottom", # Legend position
        legend.title = "",
        text = c("10:00-12:00\nReport due"),             
        text.pos = 23,        
        text.size = 2.5,              
        text.col = "black")
```
